### ISSUE TITLE
License

### ISSUE THREAD

**Issue by xmnlab** [cape-io/graphql-schema-org#3]
Hey everyone,

what is the license of this project? I tried to find it but if no success.

thanks

**Comment by webmasterkai** [comment]
It's as permissive as https://schema.org/docs/terms.html will allow. Have any advice there?

**Comment by xmnlab** [comment]
thanks for the feedback @webmasterkai !

I am asking that to check if it is a opensource project and maybe contribute to this project. 

it seems it uses cc-by-sa but for software it is not recommended https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

currently we are implement schema.org types on graphql but it could be very hard to do it manually .. so I am investigante what options we have now.

thanks @webmasterkai !

**Comment by webmasterkai** [comment]
If you want to make a PR that includes a license file to your liking I'd be more than happy to merge it :-)

**Comment by webmasterkai** [comment]
Awesome, thanks again!

**Comment by xmnlab** [comment]
thanks @webmasterkai !
